name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Add your build commands here
          echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Test job 1
        run: |
          echo "This job tests something"

      - name: Test job 2
        run: |
          echo "This job tests something, but takes more time than test-job1."
          echo "After the echo commands complete, it runs the sleep command for 20 seconds"
          echo "which simulates a test that runs 20 seconds longer than test-job1"
          sleep 20

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          # Add your deployment commands here
          echo "Deploying something from the $GITHUB_REF branch."
        env:
          GITHUB_REF: ${{ github.ref }}
